ci: Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -5,12 +5,10 @@ on:
     branches:
       - main
       - developer
-      - release
   pull_request:
     branches:
       - main
       - developer
-      - release
 
 jobs:
   Preflight:
@@ -19,17 +17,15 @@ jobs:
     steps:
       - uses: actions/checkout@v2
 
-      - name: Set up JDK 17
-        uses: actions/setup-java@v3
+      - uses: actions/setup-java@v3
         with:
           java-version: '17'
           distribution: 'temurin'
           cache: 'maven'
 
-      - name: Verify commit messages
-        run: |
-            commit_message=$(git log -1 --pretty=format:"%s")
-            echo "$commit_message" | grep -E '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.+\))?!?: .+$' || (echo "Commit message validation failed" && exit 1)
+      - run: |
+          commit_message=$(git log -1 --pretty=format:"%s")
+          echo "$commit_message" | grep -E '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.+\))?!?: .+$' || (echo "Commit message validation failed" && exit 1)
 
   Build:
     runs-on: ubuntu-latest
@@ -38,15 +34,13 @@ jobs:
     steps:
       - uses: actions/checkout@v2
 
-      - name: Set up JDK 17
-        uses: actions/setup-java@v3
+      - uses: actions/setup-java@v3
         with:
           java-version: '17'
           distribution: 'temurin'
           cache: 'maven'
 
-      - name: Build with Maven
-        run: mvn -B package --file pom.xml
+      - run: mvn -B package --file pom.xml
 
   Teste:
     runs-on: ubuntu-latest
@@ -55,15 +49,13 @@ jobs:
     steps:
       - uses: actions/checkout@v2
 
-      - name: Set up JDK 17
-        uses: actions/setup-java@v3
+      - uses: actions/setup-java@v3
         with:
           java-version: '17'
           distribution: 'temurin'
           cache: 'maven'
 
-      - name: Run unit tests
-        run: mvn test -Dtest=ProgramaTesteUnitario
+      - run: mvn test -Dtest=ProgramaTesteUnitario
 
   SonarCloud:
     runs-on: ubuntu-latest
@@ -72,27 +64,23 @@ jobs:
     steps:
       - uses: actions/checkout@v2
 
-      - name: Set up JDK 17
-        uses: actions/setup-java@v3
+      - uses: actions/setup-java@v3
         with:
           java-version: '17'
           distribution: 'temurin'
           cache: 'maven'
 
-      - name: Cache SonarCloud packages
-        uses: actions/cache@v2
+      - uses: actions/cache@v2
         with:
           path: ~/.sonar/cache
           key: ${{ runner.os }}-sonar
 
-      - name: Install SonarCloud scanner
-        run: |
+      - run: |
           curl -sSLo /tmp/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
           unzip /tmp/sonar-scanner.zip -d ~/.sonar/
           echo 'export PATH="$PATH:$HOME/.sonar/sonar-scanner-4.6.2.2472-linux/bin"' >> $GITHUB_ENV
 
-      - name: Run SonarCloud Scan
-        env:
+      - env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.11-9/x64
