ci: Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -1,4 +1,4 @@
-name: Java CI with Maven and SonarCloud
+name: Java CI with Maven
 
 on:
   push:
@@ -11,47 +11,84 @@ on:
       - developer
 
 jobs:
-  build:
+  Preflight:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
+      - uses: actions/checkout@v2
 
-      - name: Set up JDK 17
-        uses: actions/setup-java@v2
+      - uses: actions/setup-java@v3
         with:
           java-version: '17'
+          distribution: 'temurin'
+          cache: 'maven'
 
-      - name: Cache Maven packages
-        uses: actions/cache@v2
+      - run: |
+          commit_message=$(git log -1 --pretty=format:"%s")
+          echo "$commit_message" | grep -E '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.+\))?!?: .+$' || (echo "Commit message validation failed" && exit 1)
+
+  Build:
+    runs-on: ubuntu-latest
+    needs: Preflight
+
+    steps:
+      - uses: actions/checkout@v2
+
+      - uses: actions/setup-java@v3
         with:
-          path: ~/.m2/repository
-          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
-          restore-keys: |
-            ${{ runner.os }}-maven-
+          java-version: '17'
+          distribution: 'temurin'
+          cache: 'maven'
 
-      - name: Build with Maven
-        run: mvn -B package --file pom.xml
+      - run: mvn -B package --file pom.xml
 
-      - name: Test with Maven
-        run: mvn test -Dtest=ProgramaTesteUnitario
+  Teste:
+    runs-on: ubuntu-latest
+    needs: Build
 
-      - name: Download and unzip SonarScanner
-        run: |
+    steps:
+      - uses: actions/checkout@v2
+
+      - uses: actions/setup-java@v3
+        with:
+          java-version: '17'
+          distribution: 'temurin'
+          cache: 'maven'
+
+      - run: mvn test -Dtest=ProgramaTesteUnitario
+
+  SonarCloud:
+    runs-on: ubuntu-latest
+    needs: Teste
+
+    steps:
+      - uses: actions/checkout@v2
+
+      - uses: actions/setup-java@v3
+        with:
+          java-version: '17'
+          distribution: 'temurin'
+          cache: 'maven'
+
+      - uses: actions/cache@v2
+        with:
+          path: ~/.sonar/cache
+          key: ${{ runner.os }}-sonar
+
+      - run: |
           curl -sSLo /tmp/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
-          unzip -q /tmp/sonar-scanner.zip -d ~/.sonar/
+          unzip /tmp/sonar-scanner.zip -d ~/.sonar/
+          echo 'export PATH="$PATH:$HOME/.sonar/sonar-scanner-4.6.2.2472-linux/bin"' >> $GITHUB_ENV
 
-      - name: Configure SonarScanner path
-        run: echo "export PATH=\"$HOME/.sonar/sonar-scanner-4.6.2.2472-linux/bin:\$PATH\"" >> $GITHUB_ENV
-
-      - name: Run SonarScanner
-        env:
+      - env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         run: |
-          sonar-scanner \
+          export PATH="$PATH:$HOME/.sonar/sonar-scanner-4.6.2.2472-linux/bin"
+          /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.11-9/x64/bin/java -jar $HOME/.sonar/sonar-scanner-4.6.2.2472-linux/lib/sonar-scanner-cli-4.6.2.2472.jar \
             -Dsonar.projectKey=AlissonRayanss_Gestao-e-Qualidade-de-Software-A3 \
             -Dsonar.organization=alissonrayanss \
             -Dsonar.host.url=https://sonarcloud.io \
-            -Dsonar.login=$SONAR_TOKEN \
+            -Dsonar.login=$SONAR_TOKEN
+            sonar-scanner \
             -Dsonar.java.binaries=target/classes
