CI: Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -27,15 +27,14 @@ jobs:
       - name: Get last tag
         id: get_last_tag
         run: |
-          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")
+          git fetch --tags
+          LAST_TAG=$(git describe --tags --abbrev=0)
           echo "::set-output name=last_tag::$LAST_TAG"
       
-      - name: Fetch tags
-        run: git fetch --tags
-        
       - name: Verify commit messages since last tag
         run: |
-          git log --pretty=format:"%h - %s" $v1.0.0..HEAD | grep -E '^(build|chore|CI|docs|feat|fix|perf|refactor|revert|style|test)(\(.*\))?!?: .*$' | | (echo "Commit message validation failed" && exit 1)
+          LAST_TAG=$(echo "${{ steps.get_last_tag.outputs.last_tag }}")
+          git log --pretty=format:"%h - %s" $LAST_TAG..HEAD | grep -E '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.*\))?!?: .*$' || (echo "Commit message validation failed" && exit 1)
 
   Build:
     runs-on: ubuntu-latest
