CI: Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -9,8 +9,9 @@ on:
     branches:
       - main
       - developer
+
 jobs:
-  build:
+  Prelight:
     runs-on: ubuntu-latest
 
     steps:
@@ -22,10 +23,21 @@ jobs:
           java-version: '17'
           distribution: 'temurin'
           cache: 'maven'
+
+  Build:
+    runs-on: ubuntu-latest
+    needs: Prelight
+
+    steps:
+      - uses: actions/checkout@v2
+
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3
+        with:
+          java-version: '17'
+          distribution: 'temurin'
+          cache: 'maven'
        
-      - name: Run unit tests
-        run: mvn test 
-          
       - name: Get last tag
         id: get_last_tag
         run: |
@@ -42,7 +54,31 @@ jobs:
       - name: Build with Maven
         run: mvn -B package --file pom.xml
 
+  Teste:
+    runs-on: ubuntu-latest
+    needs: Build
+
+    steps:
+      - uses: actions/checkout@v2
+
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3
+        with:
+          java-version: '17'
+          distribution: 'temurin'
+          cache: 'maven'
+
+      - name: Run unit tests
+        run: mvn test 
+      
       - name: Check commit messages
         run: |
-         git log ${{ steps.get_last_tag.outputs.last_tag }}..HEAD --format=%s | grep -E "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.+\))?!?: .*$" || true
- 
+          for COMMIT in $(git log ${{ needs.Build.outputs.get_last_tag.outputs.last_tag }}..HEAD --format=%s); do
+            echo "Checking commit message: $COMMIT"
+            if [[ $COMMIT =~ ^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.+\))?!?: .*$ ]]; then
+              echo "Valid commit message: $COMMIT"
+            else
+              echo "Invalid commit message: $COMMIT"
+              exit 1
+            fi
+          done
