ci: Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -23,18 +23,10 @@ jobs:
           java-version: '17'
           distribution: 'temurin'
           cache: 'maven'
-          
-      - name: Get last tag
-        id: get_last_tag
+
+      - name: Verify commit messages
         run: |
-          git fetch --tags
-          LAST_TAG=$(git describe --tags --abbrev=0 --always)
-          echo "::set-output name=last_tag::$LAST_TAG"
-      
-      - name: Verify commit messages since last tag
-        run: |
-          LAST_TAG=$(echo "${{ steps.get_last_tag.outputs.last_tag }}")
-          git log --pretty=format:"%h - %s" v1.0.1..HEAD | grep -E '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.*\))?!?: .*$' || (echo "Commit message validation failed" && exit 1)
+          git log --pretty=format:"%h - %s" ${{ github.event.before }}..${{ github.sha }} | grep -E '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.*\))?!?: .*$' || (echo "Commit message validation failed" && exit 1)
 
   Build:
     runs-on: ubuntu-latest
@@ -68,4 +60,4 @@ jobs:
           cache: 'maven'
 
       - name: Run unit tests
-        run: mvn test 
+        run: mvn test
