build: Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -21,7 +21,11 @@ jobs:
 
       - name: Check commit messages
         run: |
-          git log --format=%s ${{ github.event.before }}..${{ github.sha }} | grep -E "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.+\))?!?: .*$"
+          COMMIT_MSG=$(git log --format=%s ${{ github.event.before }}..${{ github.sha }} | grep -E "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.+\))?!?: .*$")
+          if [ -z "$COMMIT_MSG" ]; then
+            echo "Commit message validation failed."
+            exit 1
+          fi
 
       - name: Run Tests
         run: mvn test 
